config/routes.rb
Blog::Application.routes.draw do
  resources :posts
  
  root to: 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  scope :recent, -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :json_request?

  protected

  def json_request?
    request.format.json?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.recent
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.created_by_ip = request.remote_ip

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>The Muffin Blog</title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "The Muffin Blog", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <p class="navbar-btn">
              <%= link_to "Post", new_post_path, class: "btn btn-primary" %>
            </p>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <p><%= notice %></p>
      <p><%= alert %></p>

      <%= yield %>
    </div>

    </div><!-- /.container -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, rows: 15, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
    <%= link_to 'Back', :back, class: "btn btn-link" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <h2><%= link_to post.title, post %></h2>
  <%= simple_format h(post.body.truncate(200)) %>
  <hr>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-info" %>
    <%= link_to 'Delete', post_path(@post), method: :delete, class: "btn btn-danger" %>
  </div>

  <h1><%= @post.title %></h1>

  <small>Created by IP: <%= @post.created_by_ip %></small>
</div>

<%= simple_format h(@post.body) %>